name: Release

on:
  push:
    tags: 'v*'

jobs:
  test-and-build:
    name: Test and Build
    uses: ./.github/workflows/pipeline.yml
    secrets:
      TEST_POSTGRES_PASSWORD: ${{ secrets.TEST_POSTGRES_PASSWORD }}
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test-and-build
    if: startsWith(github.event.head_commit.message, 'Test')
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set vars
        id: vars
        run: |
          COMMIT_TITLE=$(git log -1 --pretty=%B | head -n 1)
          COMMIT_BODY=$(git log -1 --pretty=%B | tail -n +3)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "RELEASE_TITLE<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Create Github Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.vars.outputs.RELEASE_TITLE }}
          body: ${{ steps.vars.outputs.RELEASE_NOTES }}
          draft: false
          prerelease: false