name: Publish API Docs to Github Pages

on:
  push:
    branches: [ "master" ]
    paths:
      - 'docs/**'

jobs:
  api-docs:
    name: Publish Swagger API Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Swagger docs
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean generateOpenApiDocs
      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact
        with:
          path: docs
      - name: Publish to Github Pages
        uses: actions/deploy-pages@v1
